# create build for local docker file

services:
  scan:
    build: .
    # mount the folders image and output
    volumes:
      - ./data/input:/input
      - ./data/output:/output
      - ./results:/results
      - ./logs:/logs
    # expose the port 8001
    ports:
      - "8001:8001"

